#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "$0")/version"

cd "$(dirname "$0")/.."

mkdir -p bin
CGO_ENABLED=0 go build -trimpath -buildvcs=false \
    -ldflags "-X main.VERSION=${VERSION} -s -w" \
    -o bin/metadata-service .
